name: "Benchmark"
on:
  push:
  workflow_call:
  workflow_dispatch:
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-test-env
      - name: Run benchmarks
        shell: bash
        run: pnpm x spec/bench/thumbdrive.bench.ts
